- .github/workflows/release.yml
* Python 3.9.x を使うように変更
* 必要モジュールインストール時に --upgrade オプションを指定
> GitHub Actionの修正

- source/explanations/screen-reader-check-android-talkback.rst
- Material Design関連リンクを更新。
- Android Developersへのリンクを削除
> Androidのコンポーネントに関連するリンクの更新

- .github/workflows/lint.yaml
- .github/workflows/release.yml
- sphinx_rtd_themeのcanonical URLの指定オプションの変更に対応
- PR作成時に各種ファイルのlintを実行するアクションを追加
> GitHub Actionsの修正と追加

- data/json/schemas/check.json
- data/yaml/checks/product/0021.yaml
- data/yaml/checks/product/0051.yaml
- data/yaml/checks/product/0081.yaml
- data/yaml/checks/product/0111.yaml
- data/yaml/checks/product/0112.yaml
- data/yaml/checks/product/0141.yaml
- data/yaml/checks/product/0172.yaml
- data/yaml/checks/product/0201.yaml
- data/yaml/checks/product/0411.yaml
- data/yaml/checks/product/0413.yaml
- data/yaml/checks/product/0441.yaml
- data/yaml/checks/product/0471.yaml
- data/yaml/checks/product/0531.yaml
- data/yaml/checks/product/0561.yaml
- data/yaml/checks/product/0562.yaml
- data/yaml/checks/product/0591.yaml
- data/yaml/checks/product/0621.yaml
- data/yaml/checks/product/0681.yaml
- data/yaml/checks/product/0682.yaml
- data/yaml/checks/product/0711.yaml
- data/yaml/checks/product/0801.yaml
- data/yaml/checks/product/0861.yaml
- data/yaml/checks/product/0921.yaml
- data/yaml/checks/product/0922.yaml
- data/yaml/checks/product/0951.yaml
- data/yaml/checks/product/1191.yaml
- tools/yaml2rst/templates/allchecks.rst
- tools/yaml2rst/templates/gl-category-id.rst
- tools/yaml2rst/yaml2rst.py
* プロダクトのチェックシートにチェック手順も表示できるようにYAMLの構造とyaml2rst.pyを見直し
* 関連してチェック内容とチェック手順の文言を調整
> チェックリストの構成変更

- tools/yaml2rst/yaml2rst.py
YAMLファイル処理時に以下のチェックを実施
* ガイドラインのID、ガイドラインのsortKey、チェックのIDがそれぞれ重複していない
* YAMLがSchemaの定義に従っている
> yaml2rst.pyにYAMLファイルの各種チェックを追加

- data/yaml/checks/product/0411.yaml
- data/yaml/checks/product/0441.yaml
- data/yaml/checks/product/0951.yaml
- check-0441: 画像の説明が適切であることの確認を追加
- check-0951: 関連するaxeのルールを追加
- check-0411: axeによるチェック方法の例を追加
> axe DevToolsを用いたチェック方法について、一部加筆

- .github/workflows/release.yml
- 一部アクションについて、最新バージョンを指定
- 利用する変数名の調整、make cleanの実行タイミングの調整
- 常にワークフロー実行時の状態に戻す
- Output some status.
> リリース時ワークフローの修正

- tools/yaml2rst/yaml2rst.py
- ツールごとのチェック方法のファイルが適切に生成されないことがある問題を修正
- cosmetic changes
> yaml2rst.py: ツールごとのチェック方法のファイルが適切に生成されないことがある問題を修正

- Makefile
- tools/yaml2rst/templates/faq/tagpage.rst
- tools/yaml2rst/templates/incfiles.mk
- tools/yaml2rst/templates/info_to_faq.rst
- tools/yaml2rst/yaml2rst.py
- FAQ関連ファイルの依存関係を追加と、Makefileの全体的な見直し
- yaml2rst.pyが生成したファイルでどのファイルからもincludeされていないファイルがないかを確認する check-includes ターゲットを追加
> Makefile改善

- tools/yaml2rst/templates/faq/index.rst
- tools/yaml2rst/templates/faq/tag-index.rst
- tools/yaml2rst/templates/faq/tagpage.rst
- tools/yaml2rst/yaml2rst.py
- FAQタグの処理を改善
- FAQの個別タグページの冒頭にもテキスト追加
> FAQタグの処理改善

- data/json/faq-tags.json
- data/yaml/faq/p0003.yaml
- source/explanations/color-only.rst
- source/explanations/grayscale.rst
- tools/yaml2rst/templates/faq/article.rst
- FAQ記事のテンプレート、関連ガイドラインの表示を修正
- グレースケール表示のブックマークレットに関するFAQ追加
> グレースケール表示のブックマークレットに関するFAQ追加

- .github/workflows/release.yml
- **アーカイブのbaseurlを修正**
- **一時的に既存のアーカイブのダウンロードをスキップして、全アーカイブをリビルド。**
> アーカイブ・ファイルのビルド時のbaseurlの指定を修正

- .github/workflows/release.yml
- **Correct the source path of the ChangeLog for the release note**
- **アーカイブのリビルドが完了したので、既存ファイルのダウンロードを再開**
> リリース・ノートのソースのパスを修正

- README.md
- **freee株式会社の表記をフリー株式会社に変更**
- **著作権表示を 2020-2024に更新**
- **freee Developers Blog -> freee Developers Hub**
> README.md内の表記の修正

- .lintstagedrc.mjs
- requirements.txt
- **lint-stagedで、*.rstに対してsphinx-lintを実行**
- **sphinx-lintをpip installするパッケージ群に追加**
> *.rstファイルのpre-commitでsphinx-lintを実行

- .lintstagedrc.mjs
- data/json/schemas/faq.json
- tools/yaml2rst/a11y_guidelines.py
- tools/yaml2rst/a11y_guidelines_initializer.py
- tools/yaml2rst/templates/en/faq/article.rst
- tools/yaml2rst/templates/ja/faq/article.rst
- **無駄な空行の出力抑制**
- **テンプレート・ファイルに対してはsphinx-lintは実行しない**
- **FAQのスキーマに関連FAQのフィールドを追加**
- **FAQの関連FAQフィールドの追加に対応**
> FAQに関連FAQのフィールドを追加

- data/yaml/faq/d0001.yaml
- data/yaml/faq/p0005.yaml
- en/source/explanations/markup-semantics.rst
- ja/source/explanations/markup-semantics.rst
- **faq-d0001:関連ガイドライン、カレン連参考情報を追加**
- **exp-markup-semantics: 関連FAQを追加**
- **faq-p0005: タグ、関連情報を見直し**
> FAQの関連情報を見直し

- ja/source/_static/a11y-gl.css
- ja/source/_static/copylink.js
- ja/source/_templates/layout.html
- **copy-linkを拡張。URLのみかタイトル+URLかを選択できる。**
- **新しいcopylinkに対応したスタイル**
- **copylinのラベルに用いる言語はhtml要素のlang属性から判断するようにしたので、事前の変数定義は不要**
> copylink拡張

- tools/yaml2x/yaml2json/yaml2json.py
- version.py
- **version.pyにチェックシートの更新日を追加**
- **yaml2json.py: チェックシートの更新日を出力するJSONに追加**
> チェックシートの更新日の情報をversion.pyに追加

- data/yaml/faq/p0001.yaml
- data/yaml/faq/p0006.yaml
- data/yaml/faq/p0007.yaml
- en/source/intro/history.rst
- ja/source/intro/history.rst
- **p0001に例を追加**
- **日付、時刻の読み上げに関するFAQ追加**
- **FAQの出力順を調整**
- **FAQ更新情報追加**
> スクリーン・リーダーによる読み上げに関するFAQの更新と追加

- requirements.txt
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/__init__.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/classes.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/config.development.yaml
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/config.production.yaml
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/config.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/config.yaml.sample
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/constants.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/info_utils.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/initializer.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/models/check.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/models/content.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/models/faq/article.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/models/reference.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/settings.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/source.py
- tools/yaml2x/libs/freee_a11y_gl/freee_a11y_gl/version_utils.py
- tools/yaml2x/libs/get_yaml_data/get_yaml_data/config.py
- tools/yaml2x/libs/get_yaml_data/get_yaml_data/process_yaml.py
- tools/yaml2x/yaml2rst/initializer.py
- tools/yaml2x/yaml2rst/path.py
- tools/yaml2x/yaml2rst/yaml2rst.py
- **Move some constants definitions from yaml2rst to freee_a11y_gl**
- **Move info links handling and version handling from get_yaml_data to freee_a11y_gl**
- **Move hard-coded values into config.py**
- **Load settings from external sources.**
- **Add sample config files.**
- **Improve baseurl handling.**
- **Improve settings handling.**
- **Eliminate some hard-coded values.**
- **Reflect the changes in freee_a11y_gl and use the default values from there.**
- **Fix version file handling.**
- **Improve URL HANdling.**
- **Some more changes for better url handling.**
- **Remove print() for debuggin.**
> yaml2x以下のリファクタリング

- data/json/faq-tags.json
- data/yaml/faq/p0009.yaml
- en/source/explanations/tab-order-check.rst
- en/source/intro/history.rst
- ja/source/explanations/tab-order-check.rst
- ja/source/intro/history.rst
- **Sort FAQ tags in alphabetical order.**
- **Add new FAQ tag keyboard-operation**
- **faq-p0009追加**
> Safariのタブフォーカスに関するFAQ追加

- tools/scripts/yaml2sheet/pyproject.toml
- tools/scripts/yaml2sheet/src/yaml2sheet/config.ini.sample
- tools/scripts/yaml2sheet/src/yaml2sheet/config.toml.sample
- tools/scripts/yaml2sheet/src/yaml2sheet/config.yaml.sample
- tools/scripts/yaml2sheet/src/yaml2sheet/config_loader.py
- tools/scripts/yaml2sheet/src/yaml2sheet/sheet_formatter.py
- tools/scripts/yaml2sheet/src/yaml2sheet/sheet_generator.py
- tools/scripts/yaml2sheet/src/yaml2sheet/yaml2sheet.py
- **Grant edit permission of protected ranges to given email address**
- **Fix column width handling.**
- **Restore the conditional formatting rules for generated result columns.**
- **yaml2sheet: bump the version.**
> yaml2sheet: 条件付き書式と列幅の制御を修正

- tools/lib/freee_a11y_gl/pyproject.toml
- tools/lib/freee_a11y_gl/src/freee_a11y_gl/yaml_processor/rst_processor.py
- tools/scripts/yaml2sheet/pyproject.toml
- **Improve :kbd: handling in rerst.**
- **The version for yaml2sheet should have been bumped with the previous change.**
> Improve :kbd: handling in yaml

- .github/workflows/release.yml
- .github/workflows/reusable-build-doc.yml
- **Remove debugging output.**
- **Show a message when there was no reusable artifact.**
- **Add actions: read permission.**
> Enable reusable artifacts to be downloaded

- .github/workflows/release.yml
- .github/workflows/reusable-build-doc.yml
- **Check GTM_ID passing status.**
- **Pass secrets to reusable-build-doc**
> pass secrets to reusable-build-doc

- tools/lib/freee_a11y_gl/src/freee_a11y_gl/config.py
- tools/lib/freee_a11y_gl/src/freee_a11y_gl/settings.py
- **Fix get_platform_name()**
- **Change for newer pydantic.**
> minor fix for freee_a11y_gl library
